#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use CoDevelopers\WpSkeleton\Console\DatabaseCreate;
use CoDevelopers\WpSkeleton\Console\DatabaseExport;
use CoDevelopers\WpSkeleton\Console\DatabaseImport;
use CoDevelopers\WpSkeleton\Console\HelloWorld;
use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands
$application->add(new HelloWorld());
$application->add(new DatabaseCreate());
$application->add(new DatabaseExport());
$application->add(new DatabaseImport());

$application->run();
