## MySQL settings
## The name of the database for WordPress
DB_NAME:
## MySQL database username
DB_USER:
## MySQL database password
DB_PASSWORD:
## MySQL hostname
DB_HOST: 'localhost'
## Database Charset to use in creating database tables
DB_CHARSET: 'utf8mb4'
## The Database Collate type
DB_COLLATE:

## Authentication Unique Keys and Salts
## https://api.wordpress.org/secret-key/1.1/salt/
AUTH_KEY: 'put your unique phrase here'
SECURE_AUTH_KEY: 'put your unique phrase here'
LOGGED_IN_KEY: 'put your unique phrase here'
NONCE_KEY: 'put your unique phrase here'
AUTH_SALT: 'put your unique phrase here'
SECURE_AUTH_SALT: 'put your unique phrase here'
LOGGED_IN_SALT: 'put your unique phrase here'
NONCE_SALT: 'put your unique phrase here'

## WordPress Database Table prefix
TABLE_PREFIX: 'wp_'

## WordPress debugging mode
WP_DEBUG: true

## Site root URL
SITE_URL: 'http://example.dev'

## Proxy server
PROXY:
    HOST:
    PORT:
    USERNAME:
    PASSWORD:
    EXCLUDED_HOSTS:
        
## Default theme
DEFAULT_THEME: twentyseventeen